merge_coin_desc1 = "From now on, you can get Namecoin(NMC), Elastos(ELA), VCash(VCASH) for free if you are mining Bitcoin or Bitcoin cash in BTC.com mining pool."
merge_coin_desc2 = "From now on, you can get Dogecoin (PPLNS) for free if you are mining Litecoin in BTC.com mining pool."
nmc = "Namecoin (NMC)"
ela = "Elastos (ELA)"
vcash  = "VCash (VCASH)"
doge = "Dogecoin（DOGE)"
merge_coin_help_nmc = "What's NMC?"
merge_coin_help_ela = "What's ELA?"
merge_coin_help_vcash = "What's VCASH?"
merge_coin_help_doge = "What's DOGE?"