merge_coin_desc1 = "即日起在BTC.com矿池挖矿(比特币现金，比特币)的同时免费赠送域名币(NMC), 亦来云(Elastos), VCash(VCASH)。"
merge_coin_desc2 = "即日起在BTC.com矿池挖矿(莱特币LTC)的同时免费赠送狗狗币(Doge)，以PPLNS方式结算。"
nmc = "域名币 (NMC)"
ela = "亦来云 (ELA)"
vcash = "VCash (VCASH)"
doge = "狗狗币（DOGE)"
merge_coin_help_nmc = "什么是NMC?"
merge_coin_help_ela = "什么是ELA?"
merge_coin_help_vcash = "什么是VCASH?"
merge_coin_help_rsk = "什么是Doge?"