timeout: 10000

base: "https://pre.pool.btc.com"
basetwo: "https://help.pool.btc.com"
explorerBase: "https://explorer-app.api.btc.com/"

apis:
  app.banner:
    uri: "/v1/getappbanner"
    method: "GET"
  app.notice:
    uri: "/v1/announcement"
    method: "GET"

  explorer.poolRank:
      uri: "/stats/app/pool/top"
      method: "GET"
      base: "https://explorer-app.api.btc.com"
  explorer.blockList:
      uri: "/chain/app/index/block/list/"
      method: "GET"
      base: "https://explorer-app.api.btc.com"

  public.multiCoinStats:
    uri: "/v1/pool/multi-coin-stats"
    method: "GET"
  public.coinsIncome:
    uri: "/v1/coins-income"
    method: "GET"


  
  pool.hashrateHistory:
    uri: "/public/v1/pool/share-history/merge"
    method: "GET"
