timeout: 10000

base: "https://pre.pool.btc.com"

apis:
  app.banner:
    uri: "/v1/getappbanner"
    method: "GET"
  app.notice:
    uri: "/v1/announcement"
    method: "GET"
  app.versionCheck:
    uri: "/v1/versioncheck"
    method: "GET"
  app.urlConfig:
    uri: "/v1/getallurl"
    method: "GET"

  explorer.poolRank:
      uri: "/stats/app/pool/top"
      method: "GET"
      base: "https://explorer-app.api.btc.com"
  explorer.blockList:
      uri: "/chain/app/index/block/list/"
      method: "GET"
      base: "https://explorer-app.api.btc.com"

  public.multiCoinStats:
    uri: "/v1/pool/multi-coin-stats"
    method: "GET"
  public.coinsIncome:
    uri: "/v1/coins-income"
    method: "GET"

  pool.hashrateHistory:
    uri: "/public/v1/pool/share-history/merge"
    method: "GET"
  
  
  account.mergeEarnStats:
    uri: "/v1/account/merged-mining/earn-stats"
    method: "GET"
  account.mergeEarnHistory:
    uri: "/v1/account/merged-mining/earn-history"
    method: "GET"

  account.info:
    uri: "/v1/account/info"
    method : "GET"
  account.payset:
    uri: "/v1/account/pay/limit"
    method: "GET"
  account.paysetAddressUpdate:
    uri: "/v1/account/address/update"
    method: "POST"
  account.paylimitUpdate:
    uri: "/v1/account/pay/limit"
    method: "POST"
  account.minerConfig:
    uri: "account/sub-account/info"
    method : "GET"
  account.earnStats:
    uri: "/v1/account/earn-stats"
    method : "GET"