timeout: 10000

base: "https://pre.pool.btc.com"

apis:
  app.banner:
    uri: "/v1/getappbanner"
    method: "GET"
  app.notice:
    uri: "/v1/announcement"
    method: "GET"
  app.versionCheck:
    uri: "/v1/versioncheck"
    method: "GET"
  app.urlConfig:
    uri: "/v1/getallurl"
    method: "GET"

  explorer.poolRank:
      uri: "/stats/app/pool/top"
      method: "GET"
      base: "https://explorer-app.api.btc.com"
  explorer.blockList:
      uri: "/chain/app/index/block/list/"
      method: "GET"
      base: "https://explorer-app.api.btc.com"

  public.multiCoinStats:
    uri: "/v1/pool/multi-coin-stats"
    method: "GET"
  public.coinsIncome:
    uri: "/v1/coins-income"
    method: "GET"

  pool.hashrateHistory:
    uri: "/public/v1/pool/share-history/merge"
    method: "GET"
  
  
  account.mergeEarnStats:
    uri: "/v1/account/merged-mining/earn-stats"
    method: "GET"
  account.mergeEarnHistory:
    uri: "/v1/account/merged-mining/earn-history"
    method: "GET"

  account.info:
    uri: "/v1/account/info"
    method : "GET"
  account.payset:
    uri: "/v1/account/pay/limit"
    method: "GET"
  account.paysetAddressUpdate:
    uri: "/v1/account/address/update"
    method: "POST"
  account.paylimitUpdate:
    uri: "/v1/account/pay/limit"
    method: "POST"
  account.minerConfig:
    uri: "account/sub-account/info"
    method : "GET"
  account.earnStats:
    uri: "/v1/account/earn-stats"
    method : "GET"
  account.earnHistory:
    uri: "/subaccount/ming/earnHistory"
    method: "GET"

  account.hidden:
    uri: "/v1/account/hidden/set"
    method: "GET"
  account.hiddenCancel:
    uri: "/v1/account/hidden/cancel"
    method: "GET"

  worker.groups:
    uri: "/v1/worker/groups"
    method: "GET"
  worker.deleteGroup:
    uri: "/v1/groups/delete/"
    method: "GET"
  worker.createGruop:
    uir: "/v1/groups/create"
    method: "GET"

  worker.move:
    uri: "/v1/worker/update"
    method: "GET"
  worker.update:
    uri: "/v1/worker/update"
    method: "GET"
  worker.list:
    uri: "/v1/worker/"
    method: "GET"
  worker.detailInfo:
    uri: "/v1/worker/"
    method: "GET"
  worker.hashrateHistory:
    uri: "/v1/worker/"
    method: "GET"

  alert.settings:
    uri: "/v1/account/info"
    method: "GET"
  alert.contacts:
    uri: "/v1/alert/contacts/my"
    method: "GET"
  alert.hashrateUpdate:
    uri: "/v1/alert/setting/hashrate"
    method: "POST"
  alert.minersUpdate:
    uri: "/v1/alert/setting/miners"
    method: "POST"
  alert.intervalUpdate:
    uri: "/v1/alert/setting/interval"
    method: "POST"
  alert.contactDelete:
    uri: "/v1/alert/contacts/delete"
    method: "POST"
  alert.contactCreate:
    uri: "/v1/alert/contacts/create"
    method: "POST"
  alert.contactUpdate:
    uri: "/v1/alert/contacts/update"
    method: "POST"