timeout: 10000

base: "https://pre.pool.btc.com"
basetwo: "https://help.pool.btc.com"
explorerBase: "https://explorer-dev.api.btc.com/"

apis:
  app.banner:
    uri: "/v1/getappbanner"
    method: "GET"
  app.notice:
    uri: "/v1/announcement"
    method: "GET"
  home.multiCoinStats:
    uri: "/v1/coinstats"
    method: "GET"
  pool.hashrateHistory:
    uri: "/public/v1/pool/share-history/merge"
    method: "GET"
